language: php

php:
  - 7.3
  - 7.2

addons:
  chrome: stable
  apt:
    packages:
      - chromium-chromedriver

install:
  - ln --symbolic /usr/lib/chromium-browser/chromedriver "${HOME}/bin/chromedriver"
  - cp .env.testing .env
  - travis_retry composer install --no-interaction --prefer-dist --no-suggest
  - php artisan key:generate

before_script:
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
  - php artisan serve &

script:
  - chromedriver --url-base=/wd/hub &
  - php vendor/bin/codecept run