language: php
"os": [
    "linux"
],
"dist": "xenial",

php:
  - 7.3
  - 7.2

addons:
  chrome: stable

install:
	- cd lapa/ &
  - cp .env.testing .env
  - travis_retry composer install --no-interaction --prefer-dist --no-suggest
  - artisan key:generate

before_script:
	- cd lapa/ &
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
  - php artisan serve &

script:
	- cd lapa/ &
  - php vendor/bin/codecept run

